title: jbalis webpage
description: > # this means to ignore newlines until "baseurl:"
  John Balis Blog
permalink: ':title/'
baseurl: /balisujohn.github.io/ # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: John Balis # add your name
author-img: balis.png # add your photo
about-author: >
  I am a Computer Sciences PhD Student who is broadly interested in reinforcement learning. 
  
  <br/>  <br/>  <br/>  <br/>   <br/><br/><br/><br/>

  Special thanks to Artem Sheludko for creating the free and open source template for this website.
social-twitter: johnUBalis
social-github:  balisujohn
social-linkedin: johnubalis
social-email: mylastname at wisc dot edu

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock","vendor"]
